/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./src/**/*.{astro,html,js,jsx,ts,tsx,md,mdx}'],
  theme: {
    extend: {
      colors: {
        // Light warm-neutral theme. One brand accent (deep teal); green/red/amber
        // reserved for allow/deny/escalate decision semantics.
        'on-secondary-container': '#14532d',
        'inverse-primary': '#5eead4',
        'on-error': '#ffffff',
        tertiary: '#b45309',
        'primary-fixed-dim': '#115e59',
        'surface-dim': '#f5f5f4',
        'inverse-on-surface': '#fafaf9',
        'error-container': '#fee2e2',
        'on-error-container': '#7f1d1d',
        'secondary-fixed-dim': '#15803d',
        'on-primary': '#ffffff',
        'primary-fixed': '#115e59',
        'primary-container': '#ccfbf1',
        'on-primary-container': '#134e4a',
        'tertiary-fixed-dim': '#b45309',
        'on-tertiary-fixed': '#451a03',
        'secondary-fixed': '#bbf7d0',
        'on-background': '#1c1917',
        background: '#fafaf9',
        'surface-container-high': '#f5f5f4',
        'surface-bright': '#ffffff',
        'outline-variant': '#e7e5e4',
        secondary: '#15803d',
        'on-tertiary-fixed-variant': '#78350f',
        surface: '#fafaf9',
        'surface-variant': '#f5f5f4',
        'tertiary-container': '#b45309',
        'surface-container-low': '#fcfcfb',
        'surface-container-highest': '#efeeec',
        'on-secondary-fixed': '#14532d',
        primary: '#0f766e',
        'on-primary-fixed': '#ffffff',
        'secondary-container': '#dcfce7',
        'on-secondary': '#ffffff',
        'surface-container': '#ffffff',
        error: '#b91c1c',
        'surface-tint': '#0f766e',
        'on-tertiary-container': '#78350f',
        'inverse-surface': '#1c1917',
        'on-tertiary': '#ffffff',
        'on-surface-variant': '#57534e',
        'tertiary-fixed': '#fed7aa',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#1c1917',
        'on-secondary-fixed-variant': '#166534',
        ink: '#1c1917',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '4px',
        gutter: '24px',
        'container-max': '1440px',
        'margin-mobile': '16px',
        'margin-desktop': '48px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'headline-md': ['Schibsted Grotesk', 'sans-serif'],
        'headline-lg': ['Schibsted Grotesk', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Schibsted Grotesk', 'sans-serif'],
        'code-md': ['JetBrains Mono', 'monospace'],
        'body-sm': ['Inter', 'sans-serif'],
        display: ['Schibsted Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        // Strict scale: 12 / 14 / 16 / 20 / 32 / display-clamp. Nothing else.
        'headline-md': ['20px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.08em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'code-md': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        display: ['clamp(40px, 5.5vw, 68px)', { lineHeight: '1.05', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};