FROM postgres:14

ENV POSTGRES_DB=securenet_db \
    POSTGRES_USER=secureagent \
    POSTGRES_PASSWORD=securepassword

COPY src/database/schema.sql /docker-entrypoint-initdb.d/01_schema.sql
COPY src/database/migrations/ /docker-entrypoint-initdb.d/

EXPOSE 5432
