"""initial_schema

Revision ID: 1fea02894719
Revises: 
Create Date: 2026-05-24 01:16:40.521661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fea02894719'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('circuit_breaker_state',
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('failures', sa.JSON(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('tripped_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('kill_switch_state',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('armed', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_by', sa.String(length=255), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_kill_switch_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('agent_capabilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('capability_name', sa.String(length=100), nullable=False),
    sa.Column('capability_level', sa.Integer(), nullable=True),
    sa.Column('is_allowed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'capability_name', name='uq_agent_capability')
    )
    op.create_table('audit_log_index',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('vault_path', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('auth_events',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('challenge_nonce', sa.LargeBinary(), nullable=True),
    sa.Column('signature', sa.LargeBinary(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('containers',
    sa.Column('container_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('cpu_limit', sa.Float(), nullable=True),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=True),
    sa.Column('network_mode', sa.String(length=50), nullable=True),
    sa.Column('read_only_root', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('container_id')
    )
    op.create_table('decision_log',
    sa.Column('decision_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('request_hash', sa.LargeBinary(), nullable=True),
    sa.Column('tier1_result', sa.String(length=10), nullable=True),
    sa.Column('tier2_pii_count', sa.Integer(), nullable=True),
    sa.Column('tier2_entities', sa.JSON(), nullable=True),
    sa.Column('tier3_safe', sa.Boolean(), nullable=True),
    sa.Column('tier3_confidence', sa.Float(), nullable=True),
    sa.Column('tier3_threats', sa.JSON(), nullable=True),
    sa.Column('tier3_reasoning', sa.Text(), nullable=True),
    sa.Column('final_decision', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_table('intent_capsules',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('original_goal', sa.Text(), nullable=False),
    sa.Column('approved_actions', sa.JSON(), nullable=True),
    sa.Column('forbidden_actions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('reasoning_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('input_prompt', sa.Text(), nullable=True),
    sa.Column('reasoning_steps', sa.Text(), nullable=True),
    sa.Column('final_decision', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reasoning_logs')
    op.drop_table('intent_capsules')
    op.drop_table('decision_log')
    op.drop_table('containers')
    op.drop_table('auth_events')
    op.drop_table('audit_log_index')
    op.drop_table('agent_capabilities')
    op.drop_table('users')
    op.drop_table('policies')
    op.drop_table('kill_switch_state')
    op.drop_table('circuit_breaker_state')
    op.drop_table('agents')
    # ### end Alembic commands ###
